#+STARTUP: showall
#+PROPERTY: header-args :results silent

* Emacs
[[https://github.com/zsxh/emacs.d][My Emacs Config]]

* Env 环境变量
  Install =zsh=, =prezto= first, then
  #+BEGIN_SRC shell
    ln -sf `pwd`/env/myzshenv ~/.myzshenv
    ln -sf `pwd`/env/zpreztorc ~/.zpreztorc
    echo "source \"${HOME}/.myzshenv\"" >> ~/.zshenv
  #+END_SRC

  pyenv 注意事项，~​/.pyenv/shims 有时候会 break $PATH 的脚本，比如 "pyenv: envsubst/gettext... command not found"
  试下 ~pyenv rehash~
  https://github.com/pyenv/pyenv/issues/1112
  https://github.com/pyenv/pyenv/issues/688

* Xmodmap 键位映射
  #+BEGIN_SRC shell
    ln -sf `pwd`/.Xmodmap ~/
  #+END_SRC

  - Not Working
    - [[https://www.reddit.com/r/archlinux/comments/abfuov/xmodmap_and_xkbset_settings_are_reset_to_default/][xmodmap and xkbset settings are reset to default after system goes to sleep/standby]]
    - [[https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4][故障排除-从待机状态恢复后]]
    - [[https://superuser.com/questions/393423/the-symbol-and-systemctl-and-vsftpd][The @ symbol and systemctl and vsftpd]]

* Firefox Layout
  set the pref ~toolkit.legacyUserProfileCustomizations.stylesheets~ to =true= in ~about:config~
  copy ./firefox/chrome directory into ~/.mozilla/firefox/${some-hash-code}.dev-edition-default/

  kwin 去除标题栏，安装 systemsettings，窗口控制

* Terminal
** Alacritty
  Install =alacritty= fisrt
  #+begin_src shell
    mkdir -p ~/.config/alacritty
    ln -sf `pwd`/terminal/alacritty.yml ~/.config/alacritty/
  #+end_src
** Tmux
  #+begin_src shell
    ln -sf `pwd`/terminal/.tmux.conf ~/
  #+end_src
** Truecolor and Italic support
   https://github.com/syl20bnr/spacemacs/wiki/Terminal
  #+begin_src shell
    tic -x -o ~/.terminfo `pwd`/terminal/xterm-24bit.terminfo
  #+end_src

* Vim
  #+BEGIN_SRC shell
    ln -sf `pwd`/.vimrc ~/
  #+END_SRC sh

* Inputrc
  #+BEGIN_SRC shell
    ln -sf `pwd`/.inputrc ~/
  #+END_SRC

* Podman, Skopeo, Buildah, Podman Compose

阿里云 https://cr.console.aliyun.com/undefined/instances/mirrors 镜像加速器管理页

https://help.aliyun.com/document_detail/60750.html

#+begin_quote
说明 目前由于Docker Hub限制，导致使用镜像加速器后无法获取最新官方镜像。请暂时去掉加速器配置，直接连接Docker Hub获取。
#+end_quote

  #+begin_src shell
    # rootless mode
    sudo touch /etc/subuid /etc/subgid
    sudo usermod --add-subuids 200000-201000 --add-subgids 200000-201000 `whoami`
    podman system migrate
    # mirrors
    mkdir -p ~/.config/containers
    ln -sf `pwd`/container/registries.conf ~/.config/containers/registries.conf
    sudo ln -sf `pwd`/container/registries.conf /etc/containers/registries.conf
  #+end_src

  podman-compose 要安装 devel 分支版本的 ~yay -S podman-compose-git~，release 版好久没更新了

  podman rootless 资源限制权限问题:
  - https://stackoverflow.com/questions/62105953/podman-memlock-limits : ulimits

  +~/.config/containers/storage.conf, /etc/containers/storage.conf 的 =addtionalimagesstores= 设置为 =/var/lib/mycontainers=+

  +~sudo chmod -R a+rx /var/lib/mycontainers~+

  - 需要资源限制的就用 root 用户模式，用 addtionalimagesstores 感觉有点绕
  - rootless 限制 cpu 使用
    系统默认，用户没有 cpu cgroup controller，可以手动添加(rootless下会有性能损失)
    https://github.com/containers/podman/blob/main/troubleshooting.md#26-running-containers-with-cpu-limits-fails-with-a-permissions-error
    https://github.com/containers/podman/issues/7959 (问题讨论)
    https://wiki.archlinux.org/title/cgroups
    ~podman run --rm --cpus 1 alpine echo hello~

* Docker(已废弃)
  #+BEGIN_SRC shell
    sudo ln -sf `pwd`/container/override.conf /etc/systemd/system/docker.service.d/
  #+END_SRC


* Rime
  file:rime/README.org

* Polybar
  install ~xorg-xrandr~
  https://github.com/polybar/polybar
  #+begin_src shell
    ln -sf `pwd`/polybar ~/.config/
    ln -sf `pwd`/polybar/polybar.desktop ~/.config/autostart
  #+end_src

* Albert
  Install [[https://github.com/albertlauncher/albert][Albert]] first, then install extensions, Pressing the =spacebar= on it activated extensions.
  #+begin_src shell
    git clone --depth=1 https://github.com/albertlauncher/python.git ~/.local/share/albert/org.albert.extension.python/modules
  #+end_src

* BEGIN
** pyenv
    Install https://github.com/pyenv/pyenv
    #+begin_src shell
      pyenv install miniconda3-latest
      pyenv global miniconda3-latest
      # https://stackoverflow.com/questions/58044214/installing-anaconda-with-pyenv-unable-to-configure-virtual-environment
      # disable init of env "base"
      conda config --set auto_activate_base false
      conda update --all
      conda install python=version
    #+end_src
** dotfiles
  #+begin_src shell
    # flake8 忽略缩进警告，调整每行默认长度
    # pycodestyle 忽略缩进警告，调整每行默认长度
    ln -sf `pwd`/python/.pip ~/.pip
    ln -sf `pwd`/python/.condarc ~/
    ln -sf `pwd`/python/flake8 ~/.config
    ln -sf `pwd`/python/pycodestyle ~/.config
  #+end_src
** virtual environment examples
*** venv (deployment projects)
    https://docs.python.org/3/tutorial/venv.html
    #+begin_src shell
      # dir path ./venv is for emacs lsp-python-ms server
      python -m venv ./venv
      source venv/bin/activate
      deactivate
      pip freeze > requirements.txt
      pip install -f requirements.txt
    #+end_src
*** conda virtual environment (machine-learning researches)
    https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#
    #+begin_src shell
      conda create --name(-n) machine-learning python=3.8
      conda env export > environment.yml
      conda env create -f environment.yml
      conda activate machine-learning

      # specifying a location for an environment
      conda create --prefix ./envs jupyterlab
      conda activate ./envs
      conda deactivate
    #+end_src

* Rustfmt
  #+begin_src shell
    ln -nsf `pwd`/rust/rustfmt ~/.config/
    ln -sf `pwd`/rust/config ~/.cargo/
  #+end_src

* NodeJs

** fnm

https://github.com/Schniz/fnm

#+begin_src shell
  curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "$HOME/.config/fnm"
  mkdir ~/.config/fnm/zfunc
  fnm completions --shell=zsh > ~/.config/fnm/zfunc/_fnm
#+end_src

** nvm (废弃)
  Install ~nvm~
  #+begin_src shell
    # npm get registry
    npm config set registry https://registry.npm.taobao.org
    # yarn config get registry
    yarn config set registry https://registry.npm.taobao.org/
  #+end_src

* Proxy

* 显卡

  自动最新驱动: linux-latest, linux-latest-nvidia, linux{num}-nvidia, nvidia-utils, lib32-nvidia-utils

  linux-lastest 依赖 linux{num}
  linux-latest-nvidia 依赖 linux{num}-nvidia
  上面都是同一个人打的包，依赖没问题，升级的时候得看 nvidia 的版本是否都升上去了

  手动指定驱动版本，可以自由选择内核，nvidia驱动更新较慢，升级时小心处理冲突(比如有个别人打包的新版的nvidia-utils...)
  linux{num}, linux{num}-nvidia-{NUM}xx, nvidia-{NUM}-utils, lib32-nvidia-{NUM}xx-utils

  ps: pacman IgnorePkg 好像无法完全杜绝冲突的情况

  https://github.com/Askannz/optimus-manager

  #+begin_src shell
    cp `pwd`/optimus-manager/optimus-manager.conf /etc/optimus-manager/optimus-manager.conf
  #+end_src

  jounalctl 看见 acpi 错误导致触摸板加载失败，
  修改 /etc/default/grub  防止 acpi 错误

  #+BEGIN_SRC conf
    #GRUB_CMDLINE_LINUX_DEFAULT="splash quiet udev.log_priority=3 acpi_osi=! acpi_osi='Windows 2009'"
    GRUB_CMDLINE_LINUX_DEFAULT="splash quiet intel_iommu=on udev.log_priority=3"
  #+END_SRC

  =sudo update-grub=

  https://wiki.archlinux.org/index.php/PRIME

* Emacs, ibus-rime 中文输入法

  https://coldnew.github.io/576cfa12/
  http://liyanrui.is-programmer.com/posts/13324.html
  https://yangyingchao.github.io/emacs/2014/11/17/emacs-ibus.html
  ~pacman -S xorg-font-util~
  #+begin_src shell
    ln -sf `pwd`/.xprofile ~/.xprofile
  #+end_src

* Bluetooth

** 一般情况
   install =pulseaudio-bluetooth, bluez-utils(providing the bluetoothctl)=

   #+begin_src example
   $ bluetoothctl
   > power on
   > ...
   > scan on
   > ..
   > pair 28:...
   > ...
   > connect 28:...
   #+end_src

   Pairing works, but connecting does not

   https://wiki.archlinux.org/index.php/Bluetooth_headset#Pairing_works,_but_connecting_does_not

   ~journalctl -xe~, you might see ~bluetoothd[5556]: a2dp-sink profile connect failed for 00:1D:43:6D:03:26: Protocol not available~,
   that may be due to the =pulseaudio-bluetooth= package not being installed.

# TODO: bluetooth microphone
https://wiki.archlinux.org/index.php/Bluetooth_headset#HFP_not_working_with_PulseAudio

PulseAudio does not detect my bluetooth headset microphone.
I see no mention of microphone in the Bluetooth wiki nor the Bluetooth Headset wiki.
https://bbs.archlinux.org/viewtopic.php?pid=1921917#p1921917/
https://bbs.archlinux.org/viewtopic.php?id=209979

Refused to switch profile to headset_head_unit: Not connected
https://bbs.archlinux.org/viewtopic.php?id=251719
https://askubuntu.com/questions/831331/failed-to-change-profile-to-headset-head-unit

** Xbox One Controller wireless

   https://wiki.archlinux.org/index.php/Gamepad#Xbox_Wireless_Controller_/_Xbox_One_Wireless_Controller

   要想 disable ertm 生效，之前需要先把之前的连接配置删掉(bluetoothctl -> remove ...)

* FAQ
** A stop job is running for session c2 of user ...
   #+begin_src shell
     sudo systemctl edit systemd-timesyncd.service
   #+end_src

   #+begin_example
     [Service]
     TimeoutStopSec=1s
   #+end_example

   save as "systemd-timesyncd.service.d/override.conf" file

   https://www.reddit.com/r/archlinux/comments/4bawf7/a_stop_job_is_running_for_session_c2_of_user/

** Kwin 下切换应用时缩略图模糊(blurry)/分辨率低

   https://www.reddit.com/r/kde/comments/g3pr44/emacs_icon_in_thumnail_view_task_switcher_is/fnulmgd?utm_source=share&utm_medium=web2x&context=3

   Right click the title bar, more, special application settings, appearance and fixes, app desktop launcher name, force, name of launcher file without extension.

   wine 微信同样的方法可以解决

** Downgrade

   https://forum.manjaro.org/t/repair-station-workarounds-to-get-almost-stable-again-after-serious-breaking-updates/40172/2

   manjaro deppin bug 超多，升级后如果发现系统不正常了，可以考虑一下将一些包降级处理
   ~sudo pacman -S downgrade~
   比如: deepin-kwin 5.2.0.3 导致窗口无法移动
   ~sudo downgrade deepin-kwin~ 选择之前没问题的版本 5.2.0.2

** Installing dig & nslookup on ArchLinux
   ~sudo pacman -S bind~

** git 中文路径编码

   ~git config --global core.quotepath false~

   core.quotepath设为false的话，就不会对0×80以上的字符进行quote

   https://git-scm.com/docs/git-config#git-config-corequotePath

** kwin 崩了

https://archived.forum.manjaro.org/t/cant-move-windows-no-window-borders/90779
Can’t move windows. No window borders. can't use alt-tab. can't even move it.

~kwin-x11 2>&1 1>/dev/null &~

~deepin-wm --replace &~

dde 下找到 kwin shortcuts 配置文件 file:~/.config/kglobalshortcutsrc

kde 快捷键配置文件。。。
https://forum.kde.org/viewtopic.php?t=151477



* XPS15 9570

  https://wiki.archlinux.org/index.php/Dell_XPS_15_9570 archlinux 的文档真是个宝藏

** BIOS 固件升级

   https://wiki.archlinux.org/index.php/Dell_XPS_15_9570#EFI_firmware_updates

   固件升级到 1.15.0，风扇噪音问题得到明显改善，1.16.0及以上版本，cpu Undervolting(手动降频)有些问题，暂时没必要更新

** yay aur 安装出现 python 依赖问题
   ~pyenv global system~ pyenv 修改了 python PATH，aur 上的依赖就找不到，编译时先将 python 路径设回系统默认

* 亮度

  #+begin_src bash
    # xrandr | grep -v disconnected | grep connected
    xrandr --output eDP-1-1 --brightness 0.5
  #+end_src

* 字体
https://szclsya.me/zh-cn/posts/fonts/linux-config-guide/
* battery & performance

https://github.com/georgewhewell/undervolt

https://github.com/AdnanHodzic/auto-cpufreq ~sudo pacman -S auto-cuprfreq~


* Steam Proton

proton 5.13 issue

https://github.com/ValveSoftware/Proton/issues/4289#issuecomment-727329572

~sudo pacman -S vulkan-tools~

#+begin_src shell
  vulkaninfo |grep deviceName
#+end_src

启动命令: DXVK_FILTER_DEVICE_NAME="YOUR GPU DEVICENAME" %command%

* intel wifi

https://archived.forum.manjaro.org/t/weak-wifi-signal-intel-wireless-3165/84579
https://archived.forum.manjaro.org/t/qca9377-network-manager-idle-disconnect-issue/142151
